#!/bin/sh
# Copyright (C) 2006 OpenWrt.org
# Copyright (C) 2010 Vertical Communications

clean_up_upgrade() {
	[ -e /overlay/firmware.img ] && rm /overlay/firmware.img
}

boot_hook_add preinit_main clean_up_upgrade
